language: node_js
node_js:
  - "6"
addons:
  firefox: "49.0"
  sauce_connect:
    username: "date-time-format-timezone"
    access_key: "***********************"
install:
  - npm install
before_script:
  - npm install -g grunt
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - echo 'America/Los_Angeles' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
script: grunt